### ISSUE TITLE
How to convert from myslq to flatfile?

### ISSUE THREAD

**Issue by bloggy1982** [mcMMO-Dev/mcMMO#1401]
Hi,
due to database problems I want to switch from mysql to flatfile. How can I do this? Are there any commands?

**Comment by skyreacher** [comment]
I just want to leave a comment for others who struggle to convert from SQL to flatfile. This is how I managed to actually migrate my data:

1. configre mcMMO to use the flatfile but make sure you have correct connection settings to the database in your config file.
2. now something important which was not obvious to me first: the mcconvert command only migrates data for users who already exist in the flat file! This was my main issue. You must create entries for missing users in the flat file first, otherwise they won't be migrated. This could/should be improved in mcMMO, since it's a real pain to prepare the flat file manually. For each line in mcmmo.users you need the player's minecraft name and UUID.
3. once the mcmmo.users flatfile is prepared, start the server up
4. type `mcconvert database sql` on the server console to migrate the data from database to flatfile.

I hope this can help others who also want to migrate from database to flat file.

**Comment by gerardvanschip** [comment]
Hi guys. I have tried all suggestion, including skyreachers suggestion in adding user details, no dice. It wont migrate mysql data to the flatfile database. I really want to get this migrated. Anyone got any suggestions?

**Comment by gerardvanschip** [comment]
Btw, its /mcconvert database mysql to go from mysql to flatfile and /mcconvert database flatfile to go from flatfile to myql
