### ISSUE TITLE
Remove "you ready your fists" message

### ISSUE THREAD

**Issue by JeremyPark123999** [mcMMO-Dev/mcMMO#1521]
Hi, I am new to using mcMMO, but after I installed it, I started getting more and more annoyed by the spam of the message "you ready your fists" or "you ready your axe" and so on. I was wondering, is there a way to disable those messages?

**Comment by sneakret** [comment]
The reason "because you wouldn't be able to tell anymore if an ability is about to get activated" seems to assume that everyone cares. I know I can't speak for everyone, but don't actually care if the ability is about to get activated. I'd prefer not to know, because it is almost always an accident for me. It happens when I open doors, open chests, etc. I just want the spam to stop. I. Do. Not. Care. I don't want to know. Let me accidentally activate it.
