### ISSUE TITLE
How to disable /repair mcMMO command

### ISSUE THREAD

**Issue by pilot3101** [mcMMO-Dev/mcMMO#1972]
Hey!

How do I disable the /repair command that mcMMO has?

Thanks!

Have a great day!

**Comment by Flexo013** [comment]
Please re-open this issue.

I want my players to have /repair from Essentials and not /repair from mcMMO. Frankly I would like to disable the entire repair skill from mcMMO and everything it does, including the commands it requires. I know that I can deny my players the permission to us /repair from mcMMO using `-mcmmo.commands.repair` as a permission, however this just gives them the message "Insufficient permissions." when they try /repair, instead of Essentials repair taking over.

It would be a nice feature to have a `enabled: true|false` for each skill. That way we can choose which skills of mcMMO we would like to use.

**Comment by madtomic** [comment]
I like an enabled: true|false for each skill

**Comment by Glitchfinder** [comment]
Unless the API has been significantly altered since the last time I looked, there is no way to enable/disable commands on the fly without using internal values that are inaccessible for a reason. Yes, there are plugins that do it. No, they should not be doing it. No, mcMMO will not do so until a way to legitimately disable commands using the API is added.

**Comment by Flexo013** [comment]
Understandable. However I see that mcMMO makes sure to overwrite the `/repair` that Essentials provides. Maybe you could provide an option which allows the user to set which command takes priority.

**Comment by Glitchfinder** [comment]
That isn't a matter of overwriting a command. It is a load order issue. If you absolutely must have the /repair from Essentials, refer to their config files. There should be a bit about prioritizing load order to ensure commands get overwritten.

**Comment by t00thpick1** [comment]
This can be done using the commands.yml feature that I personally built into bukkit several months ago

**Comment by Flexo013** [comment]
Thanks a bunch!
