### ISSUE TITLE
Disable level up messages!

### ISSUE THREAD

**Issue by ghhsheshrh** [mcMMO-Dev/mcMMO#2212]
There is no current way to disable level up messages which spam the player if XP rates are very high, could you please add this to the config which would act in the same way as disabling the ability messages? Thanks.

**Comment by Petoovee** [comment]
How about changing their frequency? I've added it to my server as a very subtle plugin, where even the best of players only get a third of the standard values. I wanted it not as a main feature but more like a mildly interesting thing to pop up every now and then. 

I'd love to see only ever ten levels announced, lest I have to go through the entire configuration to buff effects and lower required experience. Yet that would still prove insufficient, since that would mean all the soft "steps" of going from 0.01% to 0.011% double drop would no longer be possible. 

Please reconsider your decision!
