### ISSUE TITLE
timings performance

### ISSUE THREAD

**Issue by HavenServer** [mcMMO-Dev/mcMMO#2421]
0.05%    45.73%     12.90 s        22.87 ms     0.0           0.6k     Task: PlayerProfileLoadingTask$ApplySuccessfulProfile(Single)

1.5.02-snapshot-b23

**Comment by k3ldon** [comment]
:O me too, mcMMO v1.5.01-SNAPSHOT

0.14%	  50.48%	  0.08 s	    25.24 ms	 0.0	       0.0k	    Task: PlayerProfileLoadingTask$ApplySuccessfulProfile(Single)

**Comment by xion87** [comment]
i have the same issue that cause tps drop 
0.55% 1,213.35% 22.45 s 606.67 ms 0.0 0.0k Task: PlayerProfileLoadingTask$ApplySuccessfulProfile(Single)

**Comment by electronicboy** [comment]
Don't post just one row, post a link to your timings report. You could be accusing mcMMO when your issue is actually elsewhere.

However, mcMMO is threaded, most of what occurs happens in a separate thread away from the main server thread so the TPS drop is minimal. (in fact, if the timings from mcMMO was really 1213.35% on the main thread, your server wouldn't have any TPSs...)

Also, that's ran as an async thread, so I doubt that's actually affecting performance.

**Comment by k3ldon** [comment]
![image](https://cloud.githubusercontent.com/assets/8853186/6183680/e7368988-b336-11e4-9173-f3fb00440f5a.png)
