### ISSUE TITLE
Does mcmmo support for offline-mode server?

### ISSUE THREAD

**Issue by TonyFoster** [mcMMO-Dev/mcMMO#2455]
My server receive a serious problem when UUID upgrade conversion.

So, can I explain and ask help for a problem which only happen in offline-mode server?

**Comment by TonyFoster** [comment]
Sorry, I should explain this problem directly.

Problem is:
When mcmmo start a UUID upgrade conversion, plugin will try to get players UUID from MOJANG.
If server run on offline-mode then player will get a UUID from server but not MOJANG.
That means if server run on offline-mode, mcmmo will get wrong UUID when doing a UUID upgrade conversion.

**Comment by t00thpick1** [comment]
We do not directly support offline mode,  if something isn't working right only on offline mode, I'm not going out of my way to fix it, although I don't actively look for ways to break it either.  I recommend just finding a way of updating your UUID's independently, because everything but the converter should work for you.
