### ISSUE TITLE
fishing bite chance

### ISSUE THREAD

**Issue by Ericyeah** [mcMMO-Dev/mcMMO#2502]
If you have lure on a fishing rod, can the bite chance upper be comboed with the bite chance upper someone with a high MCMMO lvl.

**Comment by TfT-02** [comment]
I personally believe that having a higher bite chance with higher fishing levels unbalances the fishing skill. This is because at higher fishing levels, you will be able to catch fish a lot quicker, thus will be able to level up a lot easier.

There is still a small boost to your bite rate which is unlocked by the Fishing skill, it activates if you're fishing in a boat or in a ocean biome. Though last time I checked, this feature was broken because the API it uses in Bukkit was broken. I do not know if it has been fixed since by the Spigot team.

**Comment by Ericyeah** [comment]
@TfT-02 Does this mean that if you level above 875 on a base config the levels are ideally worthless?
