### ISSUE TITLE
Plugin hanging on plugin disable and crashing server.

### ISSUE THREAD

**Issue by NobleStrike** [mcMMO-Dev/mcMMO#2516]
I've has this problem before on an older version. But i figured it was patched on this update. I paid for it and did a clean install. I made sure the old mcmmo folder and folders in each world file were removed. Like before on plugin disable the plugin hung up the server on plugin disable causing it to force shut down not saving other plugins or the maps. Last time if i remember when this happened it didn't show any errors in debug mode besides what i just said. I can try that next time no one is on my server.

Here is the log. This is the entire log cut off on MCMMO disabling due to it crashing.
http://pastebin.com/WwZLm1E6

Note one other plugin had this issue with my server in the past and these events seemed to be triggered by a host change. I am unsure why that is, or what caused this issue.

Thank you for your help.

**Comment by NobleStrike** [comment]
More details. This happens on any mcmmo build mixed with any spigot version just for me for the last half year. I will open up a test clone server on another host to see if that fixes the issue. If not then it could be another plugin interfering with mcmmo.

Currently running CraftBukkit version git-Spigot-dbe012b-61ef214 (MC: 1.8.3)  with lastest mcmmo build.

**Comment by astemus** [comment]
Like the /reload command, mcMMO has never supported any kind of process for changing the configuration without restarting the server.  Disabling the plugin while the server is still running isn't a supported feature, and is not recommended.

See these issues for more information:
https://github.com/mcMMO-Dev/mcMMO/issues/1930
https://github.com/mcMMO-Dev/mcMMO/issues/209

**Comment by EvilOlaf** [comment]
Just a side node: PlotMe is using a more aggressive way to prevent server administrators from using `/reload`. It will disable itself when a server reload is detected and will not reactivate until clean restart.

**Comment by NobleStrike** [comment]
Astemus i didn't even touch the config. This crash happens for me on /stop and /restart when the plugins are saving and disabling. Please read the pastebin for the log. Thank you.

I never do /reload it breaks way to many plugins.

**Comment by astemus** [comment]
My apologies, I didn't read your posted log.  The log is not actually providing any information on the nature of the crash, but it does show us that the crash is being initiated by the world save.  Since mcMMO has files in the world save folder, this could be why it does not progress past mcMMO and crashes.

Is this a java crash, ie, is there a java dump being generated in the server folder?  It may be more helpful to look at the details there since the server log fails to offer any real information on the nature  of the issue.

I would try and load the server without mcMMO and do as much of a flyover of the generated chunks as you can manage.  It may be that there's a bad chunk or some other anomaly that is causing the issue on your map.  I'd also delete the mcmmo_regions folder from all the world folders on your server to rule out a corruption in there as well.

If the problem persists after that, try disabling plugins that modify chunk data, chunkspawnerlimiter, worldborder, worldguard, etc.  I noticed you are using worldguard 5.9 but worldedit 6.0.2.  I'd recommend moving to worldguard 6 and making the related updates to any plugins that rely on worldguard 5.  It seems unlikely that this current issue is related, but it was just something that I noticed when looking at the plugins loading.

**Comment by NobleStrike** [comment]
Thank you for your response.
I did a clean install so that rules out mcmmo_region file corruption. All maps are functional and no signs of corruption. I have a feeling its some setting my host has set. I've seen this happen to a few other large plugins. Its as if the plugin takes longer then a few seconds to unload the server forces shutdown.

Also when you say a java dump what do you mean? Console doesn't show anything more, and the crash report folder is empty.

As for the worldgaurd 6.0.2 im waiting for it to be bug free before i change over to it.

Im going to test mcmmo alone without any other plugins installed. Then just mcmmo alone with fresh maps/files on my host and another host to rule out if its my host.

A bunch of basic trouble shooting should narrow down the issue. Ill keep you posted.

**Comment by NobleStrike** [comment]
I have confirmed it has nothing to do with my host.

Something is causing this. I will remove certain plugins tomorrow to locate if others are affecting this plugin.

**Comment by TfT-02** [comment]
That's for our block tracking system. mcmmo_regions is where mcMMO stores information about which block is placed down by a player, and which blocks aren't.

**Comment by NobleStrike** [comment]
The same issue has popped back up. running last dev build of mcmmo and CraftBukkit version git-Spigot-2ec6f06-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Log shows nothing besides it locking up on mcmmo disabling

**Comment by NobleStrike** [comment]
I messed with a ton of settings and found after changing this to false the issue stopped for me.

    Stats_Tracking: false

Not a clue what that does. But turned it to false and it magically works again.

**Comment by t00thpick1** [comment]
Cool

**Comment by Filmjolk** [comment]
Have had this issue on all and any server I had on spigot 1.8+. Several different hosts etc, dunno why not others are reporting this? Have tried shared hosting dedicated hosting and now a plain OVH dedicated. Different OS: windows, centos and ubuntu.
Things to note is that I'v only been using multicraft the whole time. I could run a regular server without multicraft to see if multicraft is the culprit.

**Comment by NobleStrike** [comment]
Most likely it has to do with some firewall blocking the plugin from communicating with the online stats or something as its only with OVH for me. Also i found that turning off stats or check for updates on other plugins with this issue fixes them too.

I dont think as many people are having this issue as we think.
