### ISSUE TITLE
ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by Solistika** [mcMMO-Dev/mcMMO#2537]
I recently updated Spigot to the latest 1.8.3 build to avoid the whole memory crashing servers problem.
Here's the Hastebin of the error.
http://hastebin.com/ereyoyazah.avrasm

**Comment by EvilOlaf** [comment]
This hastebin is empty to me?
Anyway you don't have to update to 1.8.3, even it is recommended to do so because further plugin development in general would use 1.8.3 as a base,  but you can tell BuildTools to build a 1.8 jar. The memory exploit has been fixed in this branch too.
Read the manual for BuildTools for further information.

**Comment by Solistika** [comment]
Ooops! My bad!

Here's the Error I get. 
http://hastebin.com/romipidagu.css

Here's another one I get, http://hastebin.com/atujepevaw.avrasm

**Comment by Solistika** [comment]
This is from my friend L2_Envy, sadly he doesn't have a git account, so he asked me to post it.

**Comment by t00thpick1** [comment]
None of these hastebins actually have anything in them.

**Comment by Solistika** [comment]
Yeah LOL when you take 90+ days to view the hastebin, they tend to be empty.
No biggie, I threw away mcmmo a few months ago. Not wasting time waiting on fixes that will never come :)

**Comment by t00thpick1** [comment]
Apologies for the delay,  generally I do fixes in batches when I get the free time to work on mcMMO,  and if your first post didn't work(As given by the first comment here)  I likely never saw the rest of them until this latest batch of fixes.
