### ISSUE TITLE
Custom skills

### ISSUE THREAD

**Issue by robotnikthingy** [mcMMO-Dev/mcMMO#2671]
Now that we have to pay for your plugin,I hope that means you also will look into adding new stuff people suggest

Anyways, Im suggesting for a way that for Admins to add new skills and customize them in a easy to use, admin friendly, way. So maybe add individual.yml files for each skill, and have various customization options for each skill in it.

**Comment by Tslat** [comment]
That's just not gonna happen.

Skills can't just be made by config files, they're far more in depth than that.
What ideas for skills do you have? Make suggestions

**Comment by Flavourized** [comment]
Since this was never closed, I am going to revive this a little. 

I completely agree with @Tslat that skills cannot be simply made. 

I wanted to know if there was a way for a developer to implement custom skills inside mcmmo. Ideally, I do not want to create a fork, just some api methods to create a skill, but I can see that is probably not possible (tell me if I'm wrong, am not a dev).

Question: is there a way to implement my own custom skills within mcmmo without creating a custom version?

**Comment by Tslat** [comment]
Without making the mod insanely generalised and over-encumbering, to put it simply; it's not possible.
A mod could potentially be made to do this kind of thing, but it wouldn't be very efficient.

This thread really should be closed

**Comment by skvipers** [comment]
This makes sense if gaining experience and skill levels will be implemented using another plugin. The mcmmo already has commands for issuing experience and levels. All you need is the ability to only create a custom skill.
