### ISSUE TITLE
Player fist damage.

### ISSUE THREAD

**Issue by ABNGaming** [mcMMO-Dev/mcMMO#2953]
I'm running spigot 1.8.8 
mcMMO version:  1.5.04-SNAPSHOT-b82
issue: on my server players have a fist damage that does like 3 hearts per hit which is super bad, I thought it was a spigot issue, then someone told me to remove mcMMO and the issue is by it, Any help?

**Comment by thgilfodrol** [comment]
What are the unarmed skill levels of your players? This is very likely effects of the Unarmed skill and not a bug- unless they have an impossibly low unarmed skill where it would be impossible to deal that kind of damage. If you want to disable the unarmed skill, negate the permission mcmmo.skills.unarmed for your users.

**Comment by ABNGaming** [comment]
So its normal for a player to have unarmed 19 and deal 3 hearts per hit?...
does not sound normal to me since I played on mcMMO servers before and hits were half a heart

**Comment by thgilfodrol** [comment]
Well, there's really no way to tell what is "normal" for your use case- you
did not indicate if you've independently tested the circumstances and steps
to recreate it, nor did you mention anything about your config. As such,
I'll assume you have a default config.
If I recall correctly, at Unarmed levels below 50, mcMMO adds a 3 damage
boost to Unarmed attacks- this stacks with the 1 damage vanilla Minecraft
default damage value. Coupled with Berserk, which boosts damage by 50%, you
can do 6 damage (otherwise known as 3 hearts) at levels as low as 19.
Therefore, yes, to me it does sound pretty normal. Perhaps your other
servers disabled Berserk or modified their config from the default values
to change the leveling behavior to result in different damage.

So its normal for a player to have unarmed 19 and deal 3 hearts per hit?...
does not sound normal to me since I played on mcMMO servers before and hits
were half a heart

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mcMMO-Dev/mcMMO/issues/2953#issuecomment-225151919>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AQUmXTVDC1MWegvg8QBz6oVaHw6wdlLSks5qKUDegaJpZM4IyYSe>
.
