### ISSUE TITLE
Some issues with spigot 1.10

### ISSUE THREAD

**Issue by Aslaak** [mcMMO-Dev/mcMMO#2974]
Hello,

I have some problems with mcmmo, I hope you can fix them :) 

http://hastebin.com/ipicocadoc.avrasm
http://hastebin.com/owojozalaj.avrasm
http://hastebin.com/anabobisuk.avrasm

voilà !

**Comment by quietlikeafox** [comment]
I'm not sure if I'm allowed to make a comment here but I think your problem is that you're using an old version of mcMMO. 1.5.04 is for 1.9 and 1.5.05 is for 1.10. For some plugins I know you used to be able to use an old plugin version for a new server version say a MC1.6.2 plugin but on 1.8. I might be wrong but with the changes to 1.9 and 1.10 you can't do that as easily any more. I hope you can get it working though :)
