### ISSUE TITLE
Alchemy Not Working

### ISSUE THREAD

**Issue by AdoraKitty** [mcMMO-Dev/mcMMO#3038]
This is my first time installing MCMMO, and I'm using it on spigot 1.9.4 . After extensive testing and suggestion reading for how to get the Alchemy skill to work, I've decided to post here. The higher level potions in alchemy can brew if the players manually get their skill increased, but the water lily potion does NOT brew, and brewing any potion does NOT give any experience. Have tried deleting the treasures.yml and the potions.yml and doing multiple restarts and reloads, but all to no avail.

**Comment by AdoraKitty** [comment]
Anyone?

**Comment by Nesseley** [comment]
This was broken in some parts of Spigot 1.9, maybe you just need an updated build og Spigot?

**Comment by sliverpix** [comment]
looks like this has been broken since April (and probably a bit before somewhere in spigot 1.9 at least). I can confirm with 500 alchemy, a carrot and awkward potion nothing happens. I also dont find any entries in the logs with spigot 1.11 and mcmmo 1.5.07. Ive exhausted searching the wiki and git. this is about all I can find.

Is there any update to the status of this break??

**Comment by MapleMoosey** [comment]
I have a 1.11.2 server and it's still not giving any xp for Alchemy, any updates?

**Comment by fordross** [comment]
> I have a 1.11.2 server and it's still not giving any xp for Alchemy, any updates?

I thought I was the only one, or had misconfigured something...

**Comment by MeadeRobert** [comment]
I only receive xp on 3rd brewing stage on my 1.11.2. The wiki documents that I should be receiving xp at lower stage brews. I would assume that this is still an issue. [http://mcmmo.wikia.com/wiki/Alchemy](http://mcmmo.wikia.com/wiki/Alchemy)
