### ISSUE TITLE
mcMMO Potion IDs

### ISSUE THREAD

**Issue by Daemonrds** [mcMMO-Dev/mcMMO#3111]
I am unable to find the id numbers for the mcMMO Potions so i can sell them in a shop.

**Comment by JayGamer128** [comment]
me too it worked almost with potion but i need an id or something...

**Comment by Markokeefe707** [comment]
Please help my boyfriend says that this is not his his name is Justin spiker I have been having problems with some one forwarding my information to graphic files and placing them on a billboard they have been using commandmailing.com and a cAsino app now Pokémon app they use google keep in. To  store a lot of my information they have modified my programs using JavaScript including modifying my apple safari browser they have modified my Facebook account to block me from serching they use Quora for technical support I have noticed strange emails that are encrypted with a HTML editor it tracks what website I view also it extracts the headers of every email I receive I found these emails hidden on my iPhone they even hacked my att account I called att and found that they have been using their tech support in order to assist them with a mms messaging they use Pinterest to 
Add encrypted notes their is jaylectricity too my contacts have been modified. I have contacted the California cyber authorities of my situation and will be forwarding these emails to them it looks like you have been assisting them with these hacks knowing or not this is completely invading my privacy and is illegal also unethical please email or call me a
7758461797

**Comment by PugaBear** [comment]
@JayGamer128 @Daemonrds I believe there is no ID, only metadata. This screenshot contains the metadata of a mcmmo potion, then the metadata of a normal potion. 
![image](https://cloud.githubusercontent.com/assets/12417961/23178310/8b1fbfb2-f82f-11e6-85c8-dedb1d0a028e.png) Ignore the b's, weird parsing error.
