### ISSUE TITLE
How does one add things to the .yml files?

### ISSUE THREAD

**Issue by Mangaboy5398** [mcMMO-Dev/mcMMO#3212]
Hi I'm using the latest build of McMMO (#191) and I'd want to know how I can manipulate the .yml files to allow Shields to be repaired and for additional stuff to be fished out. What I did was I added:
SHIELD:
        MinimumLevel: 0
        XpMultiplier: .5
to the repair.vanilla.yml file. I tried it even with the Shift+right Click, The shield just wont repair. Basically I just copied an entry and I changed the values to my liking. Am I doing this wrong?

**Comment by Glitchfinder** [comment]
A lot of the default repair.yml items don't use a full configuration, instead relying on things in the code. For a functional setup, it would be:

>    SHIELD:
>        MinimumLevel: 0
>        XpMultiplier: 1.0
>        ItemType: ARMOR
>        MaterialType: WOOD
>        RepairMaterial: WOOD
>        RepairMaterialMetadata: -1
>        MaximumDurability: 337
>        MinimumQuantity: 6

As well as an equivalent in the salvage config:

>    SHIELD:
>        MinimumLevel: 0
>        XpMultiplier: 1.0
>        ItemType: ARMOR
>        MaterialType: WOOD
>        SalvageMaterial: WOOD
>        SalvageMaterialMetadata: -1
>        MaximumDurability: 337
>        MaximumQuantity: 6

That said, I'm marking this as a feature request rather than a support request because this should be in the config already, and I'm probably going to need to add some relevant permissions for it.
