### ISSUE TITLE
Silk Touch Generates Double Drops For Blocks Placed By Player

### ISSUE THREAD

**Issue by Braleth** [mcMMO-Dev/mcMMO#3287]
Tested in dev build 201 with placing iron ore, diamond ore and glowstone blocks.

Using SilkTouch on these blocks immediately after placing them will grant the player double drops. Very easy way to dupe blocks/ore.

Rolled backed to build 196 to remove the dupe exploit.

**Comment by Faicu** [comment]
It's not a bug, it's a new shit feature, named: Double Drops, check on config.yml

Double DropsEdit
Double the normal loot

Double drops is a passive skill that allows the player to gain two items instead of the usual one when mining any naturally generated block found in the experience table below. The odds of this happening increase by 0.1% per level to a maximum of 100% at level 1000. It does not stack with the fortune enchantment, but does work with silk touch.

**Comment by Faicu** [comment]
http://mcmmo.wikia.com/wiki/Mining

**Comment by Braleth** [comment]
Aye, but the key point is "naturally generated blocks". It's a bug and a dupe exploit since it works on blocks that are placed by a player, as I noted.
I was able to turn a single diamond ore block into a stack in no time. Also tested with coal ore and glow stone blocks.

**Comment by t00thpick1** [comment]
Unable to reproduce using spigot 1.12.1 and mcMMo current dev build.

**Comment by Braleth** [comment]
With the latest Spigot 1.12.1 build and mcMMO build 196, the silk touch dupe isn't present. As soon as I introduce mcMMO build 201, it occurs.

I'll dig into some more testing on the test server and see if can narrow it down to another plugin. t00thpick1, safe to presume your testing was just Spigot and mcMMO b201?

**Comment by t00thpick1** [comment]
Huh. Ok glad it was solved. Now I can make a bug fix release to spigot.

**Comment by vacoup95** [comment]
This issue still exists, I'm on Minecraft 1.15.2 with the current latest McMMO build. (2.1.126-SNAPSHOT).

**Comment by nossr50** [comment]
@vacoup95 mine the block with /mmodebug and post the output
