### ISSUE TITLE
SilkTouch - Double Drop Dupe Glitch

### ISSUE THREAD

**Issue by Braleth** [mcMMO-Dev/mcMMO#3289]
https://github.com/mcMMO-Dev/mcMMO/issues/3287

and it's back again. After 2 days and completely resetting all mcMMO region data, the dupe exploit is back with mcMMO, SilkTouch and player placed blocks. The later dev builds just are not reading mcMMO region data clearly.

Rolling back to b196.

**Comment by t00thpick1** [comment]
Can you give me exact reproduction steps?

**Comment by t00thpick1** [comment]
Fixed

**Comment by Braleth** [comment]
I've just tested dev build 204 and the issue still persists. Will this require another wipe of mcMMO region data? Dev build 196 with current mcMMO region data doesn't have an issue determining which blocks are natural and which ones are placed by a player.

As for reproduction steps, there isn't much to it unfortunately: place a block (any ore, glowstone) and immediately mine it with a silktouch pick.

**Comment by Momshroom** [comment]
Not sure if this helps, but the issue seems to be entirely dependent on the mining level of the player mining the ores, EVEN if superbreaker is used.  With mining level 15 and superbreaker I do not get duplication on placed ores, with mining level 1000, I do.  With either mining level, I get mining mcmmo xp mining the placed ores.

**Comment by Braleth** [comment]
@Momshroom 
Well sure, of course you would see that. Your mining level directly impacts the double drop chance when mining a block. Kinda the purpose of mcMMO and grinding up your skills. At 1000 mining, be default, your double drop chance for mining is 100%.

**Comment by Momshroom** [comment]
@Braleth Sorry, I had herbalism on the brain.  I was thinking that with superbreaker, you always got extra drops like you do with green terra.

**Comment by mibby** [comment]
@t00thpick1 It is caused by this commit.

https://github.com/mcMMO-Dev/mcMMO/commit/e0bbe9cea4dea49528a38161f6ef982ae87b3807
https://github.com/mcMMO-Dev/mcMMO/commit/f279a979e3dc690b9e9fdc36bf66b047ee0e4523

This commit https://github.com/mcMMO-Dev/mcMMO/commit/0e51983819a2d2d595a2ccd583f203dc85def5d1 did not fix the issue.

Dupe exploit is present in dev 201, present in dev 204, fine in dev 200.

**Comment by t00thpick1** [comment]
@mibby yeah was still trying to figure out why, it was something stupid.  Should be fixed now.
