### ISSUE TITLE
add /mcmmo reload

### ISSUE THREAD

**Issue by MentosPL** [mcMMO-Dev/mcMMO#3347]
i don't want use /reload, with 60 players online and 70 plugins, 
and /reload command crashes many plugins and isn't recomended.

**Comment by Flavourized** [comment]
plugman

**Comment by MentosPL** [comment]
nope, add the command C:

**Comment by TNTUP** [comment]
That could be useful while tweaking up settings instead of rebooting the server

**Comment by Glitchfinder** [comment]
Duplicate of #209. Also, this is not possible with the current setup mcMMO has. A few years back, when that issue was being actively commented on, it was possible, and I almost got it into the plugin. However, with the way this plugin currently uses some features of Java, reloading it will break the it entirely.
