### ISSUE TITLE
Update For 1.12.2?

### ISSUE THREAD

**Issue by BrandonGamesYT** [mcMMO-Dev/mcMMO#3382]
Would really like to see a updated version for bukkit 1.12.2 If this is possible, as my server runs in bukkit 1.12.2 and the plugins we already use cannot be switched over so if theres a chance of making a 1.12 version

**Comment by CollinHerber** [comment]
You should not see any plugins break for going from bukkit to spigot.

Bukkit is now Spigot. Bukkit development no longer exists. They are essentially one of the same now.

**Comment by BrandonGamesYT** [comment]
As i also thought i stated, Not all the plugins that we are using on our bukkit server can be moved to spigot cause they are not all updated to 1.12 in spigot and some of them are main function of our server

**Comment by Glitchfinder** [comment]
This plugin does not compile against Spigot. This plugin compiles against Bukkit, as provided by Spigot. The current builds of this plugin will work on current builds of Bukkit or Spigot. This is true of any plugin that is not using internal data they shouldn't be touching (e.g. craftbukkit rather than bukkit).
