### ISSUE TITLE
DIDNT GET THE DOWNLOAD

### ISSUE THREAD

**Issue by BovBox** [mcMMO-Dev/mcMMO#3388]
I JUST BOUGHT THIS PLUGIN ON SPIGOT AND I DIDNT RECEIVE THE PLUGIN VIA EMAIL OR ON THE WEBSITE AND STILL CANT DOWNLOAD IT

**Comment by popcorn9499** [comment]
Are you sure you are logged in?

**Comment by BovBox** [comment]
Yes

Sent from my iPhone

On Jan 31, 2018, at 11:18 PM, popcorn9499 <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you sure you are logged in?

**Comment by popcorn9499** [comment]
Still happening? Try resetting the cache or something idk

**Comment by BovBox** [comment]
Yes its still happening and im getting pissed off its been 2 days since i payed for this fucking plugin

**Comment by BovBox** [comment]
i would like my fucking money back or the fucking download for the plugin or im getting my loyer involved. not playing games here

**Comment by Glitchfinder** [comment]
First, language. Second, this is a bug tracker for the plugin itself. The problem, such as it is, is a fault of Spigot and their website, and [should be taken up with them](support@spigotmc.org).

**Comment by BovBox** [comment]
Yes i will be taking this up with my fucking layer you scums

**Comment by Glitchfinder** [comment]
Again, this is an issue with Spigot and their website. There are free download links available for this plugin, including [one provided on the same page you bought it on](https://popicraft.net/jenkins/job/mcMMO/). This bug tracker is for the plugin itself, and if Spigot's website is malfunctioning, there is literally nothing anyone with access to this tracker can do to help you, because we do not work for Spigot, we do not have access to purchase records via Spigot, and we do not have any control over how their website functions. If there is a problem with Spigot's website, where you purchased this plugin, contact [Spigot's support and get it resolved](mailto:support@spigotmc.org). A lawyer won't help matters when we have literally no access to the problem in the first place.

**Comment by Deathinflames** [comment]
You mean lawyer*

Your lawyer will probably tell you that you are incompetent as you are getting mad for a problem that exists on your end, not the Spigot website nor the mcmmo devs. as Glitchfinder has already told you.
