### ISSUE TITLE
McMMO Experience file supposedly "Very Configurable"

### ISSUE THREAD

**Issue by Waplax** [mcMMO-Dev/mcMMO#3419]
As the title hints at, i find this so-called "Very configurable" Experience file to be quite dissapointing. You can change experience numbers. That is it. You cannot add blocks/items to an experience table. I have tried adding things to the different skill's experience tables with no success, which i find rather dumb to be honest. I see no reason why you should not be able to decide which blocks/items give experience in the different skills.
Is this something which will be added any time soon or is the bragging about it being "Very configurable", really just because you feel you did a good job making some numbers changeable?

**Comment by Glitchfinder** [comment]
Oh, it is very configurable. You can add blocks and items. You just have to know how to do so. [This](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html) is the full list of materials accessible in Bukkit. As is obvious when compared to the [default config](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/experience.yml), it looks very different. That's because we run the config through a formatter to make it more user friendly. We also split shared materials using [this function](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/StringUtils.java#L55) in our stringutils file.

But, it's not that hard to change what blocks and skills work for skills. I want emerald to work for Herbalism? Just add it in under the Herbalism header in the config, like so:
```        Emerald: 450```
If I want red sand to work for mining? Just add it as a line in Mining, like so:
```        Red_Sand: 150```

Just make sure not to use tabs, to match the spacing, and to use the right material names. You may need to dig them out of the relevant code I linked above, but it's *already* something that can be done by this plugin. And if you're trying to add mod blocks, that's actually going to be in [this config right here](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/mods/blocks.default.yml)
