### ISSUE TITLE
Nether Brick is not considered by MCMMO

### ISSUE THREAD

**Issue by kitokofox** [mcMMO-Dev/mcMMO#3426]
It is completely ignored by it, along with any variant of it. It cannot trigger super breaker, let the player gain experience, or get affected by double/triple drop.

**Comment by Glitchfinder** [comment]
Huh. I'd say that was an intentional design decision, because it was at the time. However, since then, end brick has been added as a default, so. If you want to add nether brick, jump to [this part of experience.yml](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/experience.yml#L187) and, under that header, add the lines "Nether_Brick: 200" and "Red_Nether_Brick: 200". Just change out the 200 with the desired exp value, and make sure to keep the same spacing as the existing config *without* using tabs. (Tabs will break a yml file)

Normally I would tag this as a support request and close it, but it honestly seems like a design oversight at this point, so it's staying open for the moment.

**Comment by Glitchfinder** [comment]
@t00thpick1 I just took in a pull request that adds this feature, at least in terms of normal nether brick. We should probably consider doing the same for nether fence and nether brick stairs, since those are the same material and both generate naturally.
