### ISSUE TITLE
Proposal: Enchantment skill

### ISSUE THREAD

**Issue by GiovanH** [mcMMO-Dev/mcMMO#3452]
I've been toying around with adding an enchantment skill. You would accumulate experience through enchanting items, and you would get passive benefits.

Ideas for passive abilities:
Experience cost discount
Chance of recovering spent lapis
Increased mending potency (https://github.com/mcMMO-Dev/mcMMO/issues/3450)
Some (careful) bonuses to enchantments (infinity/mending?)

This is a feature request, but I've actually started on the main chunk of programming the behavior. However, someone more familiar with the codebase should be involved when tying the entire skill into the existing structure.

https://github.com/GiovanH/mcMMO/commit/7553dcd2f3e2570f0341293c9c8b3202c407596e

**Comment by Glitchfinder** [comment]
One thing to note: mcMMO has been about making additions without taking things away, for the whole time it's been in progress. That's why there was the original pull request to add the potions skill sat untouched for so long - it was designed to prevent the creation of potions based on skill level.

Thus far I see no real conflict in the case of this one, though the benefits seem a bit light compared to other skills.

**Comment by GiovanH** [comment]
Yes, those were examples of the features I've already implemented rather than an inclusive list. Other ideas might be a chance to increase the actual enchantments on your items, or a chance to combine mutually exclusive enchantments (like infinity/mending) at high levels.

I think I'll start looking at the alchemy commit to get a feel for how to implement an entire skill.

**Comment by Glitchfinder** [comment]
Eh, Alchemy is kind of a bad example overall. Not to mention that the entire setup for skills has changed since then. Also, be careful with mutually exclusive enchantments, as some of them are actually mutually exclusive even when both are on the same item. (Fortune/Silk Touch, for example.)

**Comment by Glitchfinder** [comment]
Honestly? Take a look at one of the more basic gathering skills. It will have to hook in a bit differently, but those are old core skills that are more likely to be up to date.

**Comment by Glitchfinder** [comment]
Oh! I should mention that you should test and tune this at level 1000, and then 1500. A lot of mcMMO skills have two "caps", in essence, Their basic functions normally hit maximum at 1000, and their secondaries often hit maximum at around 1500. This is specific to percent-based calculations however. If you introduce a tiered system (Like Farmer's Diet, for example), those will be preset levels.

Anyway, I suppose I'm trying to say that you should test this at the maximum level for the skill to see what can be done with it, and then tune it for growth so that it doesn't seem utterly pointless when you first start using it.

**Comment by Loreweaver15** [comment]
Huh.  I misunderstood the limits--I'd thought 1000 was the Standard Cap when designing the skills he's referencing.  I'll have to keep that in mind.

**Comment by GiovanH** [comment]
So, looking at the structure of the skill, there seem to be component parts:

- "Doing the skill" based on data saved about the player
    - [Skillcontext]Listener.java handles secondary skills and anything else that doesn't require right-click to activate
    - [Skill]Treasure.java is an optional file for handling drop tables
- The data storage, which includes configuration values and saving user data
    - [Skill]Config.java is an optional file for a skill-specific yml config file
- The metadata, which includes registering the name of the skill with the help doc, /commands, and the scoreboard
    - AbilityType.java enumerates the activated skills
    - SecondaryAbility.java enumerates the passive skills
    - [Skill]Command.java handles the /[skill] command, displaying contextual data to the player
- Localization
    - Pretty much handled by localeloader, resources/locale/locale_xx_XX.properties
- Files with an unknown function
    - runnables.skills.*
    - skills.[skill].[Skill] (Maybe this contains functions for the listener to trigger???)
    - skills.[skill].[Skill]Manager (Internal registration???)
