### ISSUE TITLE
Hylian Luck only does melon seeds

### ISSUE THREAD

**Issue by alimonyaaa** [mcMMO-Dev/mcMMO#3485]
When breaking bushes with a sword; the Hylian Luck ability is supposed to drop a melon seed, a pumpkin seed, or a cocoa bean, right? I've been trying to get a cocoa bean from it; but I've gotten 50+ melon seeds without any pumpkin seeds or cocoa beans. Is this a bug?

**Comment by Adversarius13293** [comment]
It can be a bug, or a bad configuration, depending on how you want to interpret that. For me it feels more like a bug.
In the default treasures.yml you have 3 entries for [Bushes], with 100% drop chance each. Because of this, the first entry will always drop. To fix this, use 33.33% for the first entry (melon), 50% for the second (pumpkin) and 100% for the last (cocoa). Do the same for the 3 [Flowers] and the 3 [Pots] entries.

Longer explanation: If Hylian Luck activates, the code checks every treasure (loaded from the config) and tries to drop it with the configured probability. If its successful, the item drops and its done. But since its configured to 100%, it will always drop the first item of the loaded list. To get the actual probability, you have to configure it by using conditional probabilities.

The same behavior also occurs to the other treasures, like excavation. Just because you configured 1% chance for diamonds doesn't mean it will drop 1% of the time. Every other possible drop configured before the diamond entry will be processed first, and decreases the probability for following drops. But since the values are pretty low, the probability will drop from 1% to like 0.97%, which is barely noticeable. But still a bug I would like to see fixed, of course.

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.

**Comment by lexiccn** [comment]
This is still the case, the changes did not ever fix or change this behaviour.
