### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Leomixer17** [mcMMO-Dev/mcMMO#3492]
Hello, could you update the translations on [getlocalization.com](https://www.getlocalization.com/mcMMO/), since I and many other people have done a lot of work to translate this plugin and are more than 3 years that they aren't updated?

**Comment by Glitchfinder** [comment]
@t00thpick1 I actually don't know how we pulled from that site at all, do you? If worst comes to worst, could just make a regular habit of copying the information straight over.

**Comment by Leomixer17** [comment]
@Glitchfinder so why did you say that you use that site?

**Comment by Glitchfinder** [comment]
I never did. That site was largely used by some of the older devs on the project, mostly @gmcferrin. Having never directly interacted with the site myself (I don't even have an account there), I don't actually know what's involved with using it.

The reason it's gone unused for so long is that the devs who set it up no longer actively contribute to the project. In fact, the only developer who is actively contributing at the moment is toothpick, which is why I pinged him in my earlier response.

**Comment by Leomixer17** [comment]
@Glitchfinder So, will you resume it to use?

**Comment by Glitchfinder** [comment]
That mostly depends on toothpick. I rarely have the time necessary to work on this plugin anymore, which is why you mostly see me fix minor errors or work in the issue tracker here. Since nearly everyone else has also moved on to other things, that basically leaves @t00thpick1 as the only actively contributing developer at the moment, which is why the plugin's recent development has been so slow.

**Comment by t00thpick1** [comment]
im not sure I remember the password/email for that account.... I'll have to take a looksy.
