### ISSUE TITLE
plugin is not enabled

### ISSUE THREAD

**Issue by sammytaber187** [mcMMO-Dev/mcMMO#3543]
I am running spigot 1.8.8, and i downloaded the non-paywalled and also bought the payed version of the 1.8 version of mcMMO and whenever i try doing /mcmmo or /mctop or any mcmmo command, it does nothing. The console does not output any errors, and in /pl, its disabled (red) Whats going on?

**Comment by Glitchfinder** [comment]
For a starting point, when you say you are using the non-paywalled version, you're referring to [this build](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar), correct?

If that's the case, there appears to be some issue on startup. Since the console isn't outputting errors, I can't check to see what's happening there. Instead, can you copy the mcmmo folder out of plugins (make sure you have a backup, and remove the whole folder from the server's plugins folder), and let the plugin regenerate the configs from scratch. If that doesn't work, would you be able to show us the server's full startup log? There might be something we can use there, even if mcMMO isn't specifically putting out any errors.

**Comment by RyanO8** [comment]
how are you adding those labels?
