### ISSUE TITLE
Taming Exploit

### ISSUE THREAD

**Issue by GiovanH** [mcMMO-Dev/mcMMO#3563]
Tameable entities summoned with taming can be breed with each other. Simply summon one, have it sit or tie it up, walk far enough away, summon a second, and bring them together. 

This allows any user to spawn a permanent instance of any tameable animal, including horses, at any location. 

Proposed fix: make summoned animals unbreedable until they go away using the breeding timeout field.

**Comment by Zappa2510** [comment]
not a bug its been like that forever.

**Comment by GiovanH** [comment]
...so, a known exploit, then?

**Comment by Zappa2510** [comment]
not a exploit, its always been summon two, breed to get one then repeat. wolves and ocelots can be hard to find on big multiplayer worlds. this is the solution for those who want to obtain animals.

**Comment by GiovanH** [comment]
If this is going to be an official feature, at the very least it needs to be documented and toggleable in settings. Ideally it would be opt-in on top of that. 

As this mechanic is currently implemented, especially with the radius summon limit, it acts as an exploit and surprises server owners.

**Comment by Momshroom** [comment]
It's not an exploit.. and the range is configurable.  If server owners are surprised, they don't know mcmmo.

**Comment by GiovanH** [comment]
If this is intended to be a feature, at the very least it definitely needs to be documented.

**Comment by t00thpick1** [comment]
@GiovanH I like the idea of a configuration option for it.

**Comment by nossr50** [comment]
@GiovanH I'm going to consider this an exploit, I'll see what kind of solution I can implement

**Comment by Zappa2510** [comment]
I really don't see this as an issue. I know over the years it's been hard finding wolves and especially ocelots as they don't spawn normally in multiplayer. I really think it's gonna be harder once 1.14 hits.

**Comment by nossr50** [comment]
@Zappa2510 I'll think more on it

**Comment by nossr50** [comment]
This was fixed

**Comment by AlucardTheRed9** [comment]
so youre the little fucker that reported this. I was wondering why I couldnt do that anymore....... God f damn it, this shitty universe just doesnt stop taking anything good or fun from me. My health wasnt enough. -_- Enjoy your ''fix''. Tight-ass.

**Comment by AlucardTheRed9** [comment]
> This was fixed

''Fixed'' it was. Lol. I know I come off as rude or even aggressive, but maybe there is a way to re-enable this? Like, people can either find wolves and breed an army, or summon wolves and breed an army. There is only a minor difference in difficulty of acquiring them. Unless the summoned wolves are somehow superior to normal ones (or even the only ones affected by the skill), in which case the skill should be renamed 'Summoning' instead of 'Taming'. But if thats not the case, then there should be no functional difference between sumon-bred permanent wolves and normally bred ones, neyond the unique name they carry. Yet you found yourself compelled to ''fix'' that. Just..... human logic.

**Comment by nossr50** [comment]
That's a very rude way to ask for a feature or change, please behave yourself.

**Comment by GiovanH** [comment]
There was some debate in this original thread as to whether this was actually an exploit or not, but seeing outbursts like that just convinces me that it was.
