### ISSUE TITLE
Post code  1.5.09

### ISSUE THREAD

**Issue by QuiquePineyro** [mcMMO-Dev/mcMMO#3597]
I was wondering if there is I way to post the code  1.5.09? becouse there is just the code 1.6 and 1.5.00 and 1.5.0 its not compatible with some plugins like leatherheads and in 1.6 its just for the version 1.13

**Comment by Glitchfinder** [comment]
For reference, since Github doesn't exactly make browsing a repository with this many commits easy, [this](https://github.com/mcMMO-Dev/mcMMO/commit/e77801f3c1e1b0632593e565363e8b3a68877b23) is the last commit of 1.5.09 prior to the version bump, and the repository as of that commit can be viewed [here](https://github.com/mcMMO-Dev/mcMMO/tree/e77801f3c1e1b0632593e565363e8b3a68877b23).
