### ISSUE TITLE
McMMo not working

### ISSUE THREAD

**Issue by WolfBoii93** [mcMMO-Dev/mcMMO#3673]
hello, I have purchased the Dev version and tried the free version as well, downloaded it and placed it in my FTP plugins folder and restarted my server and every time it just starts up and its in red in the plugins menu. I'm not sure what to do at this point to get it to work, any help would be appreciated. Thanks for your time :)

[latest.txt](https://github.com/mcMMO-Dev/mcMMO/files/2719447/latest.txt)

**Comment by mrfloris** [comment]
Hi there,

You're running version 1.12.2, it's probably best to use 1.5.x releases for this, and use 1.6.x and 2.x for 1.13.2 and up.

```This server is running CraftBukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2) ```

Source:
https://www.spigotmc.org/resources/official-mcmmo-classic.2445/

```
1.13 Build: 1.6.0
Latest 1.12 Build: 1.5.08
Latest 1.11 Build: 1.5.08-SNAPSHOT
Latest 1.9/1.10 Build: 1.5.06
Latest 1.8 Build: 1.5.04-SNAPSHOT or (Non-Paywalled)
Latest 1.7 Release Build: 1.5.00
```

**Comment by mrfloris** [comment]
On the link I mentioned in the above post there are tabs, once you register/login, the overview/ tab has direct links to the right versions, but otherwise click on the updates/ tab and pick the version there. 

Glad to hear it has worked for you this time, have fun with mcMMO, it's an awesome plugin.

**Comment by nossr50** [comment]
@mrfloris thanks for helping this guy
