### ISSUE TITLE
The mcMMO subskills read as "testing".

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#3681]
So, um. We're having a visual issue with subskills, where they display as "Testing" in all caps. Here:

![image](https://user-images.githubusercontent.com/19168008/50732329-e0616780-1170-11e9-8409-b0138e72a51b.png)

I'm uncertain what is causing this, and I'm not sure when it began. I only became aware of it when a player brought it to my attention, wishing to know why it said testing. This was on the 4th of January. Now that said, there's a neat hover-over on them. Would this be related to a beta feature in testing? (hence the testing text)

![2019-01-06_05-10-31](https://user-images.githubusercontent.com/19168008/50732354-6b426200-1171-11e9-8799-351baa4fd2d5.gif)

**Comment by nossr50** [comment]
You're using a developer build not intended for live servers, 2.1.0 is bringing many changes and I'm currently rewriting the skill commands to make full use of JSON, because of this the skill commands look and feel is basically a placeholder.

This is not a bug, you are just running development code in its unfinished state.

**Comment by Quavelen** [comment]
Thank you, I wasn't reporting a bug. I guess I should have said that in my title. I was asking a question, which you just answered lol.
