### ISSUE TITLE
Iron Block not Repairing Shovels

### ISSUE THREAD

**Issue by Gitchagoomie** [mcMMO-Dev/mcMMO#3704]
I am playing on a Minecraft server ran by my friends dad.  I have encountered a problem where the Iron Block will not repair diamond shovels.  It will repair all other diamond based items except the shovels.  Am looking for a solution to the problem to give to my friends dad so that he can correct the issue if possible.

Thanks

**Comment by Sejsel** [comment]
Diamond shovels are listed in the [default config](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/repair.vanilla.yml#L160) and should be repairable by default.

This sounds like the server updated from 1.12 to 1.13 where DIAMOND_SHOVEL was called DIAMOND_SPADE, the server didn't load because of the now invalid name and so the item was removed instead of being properly renamed.

Should be an easy configuration fix, simply add the missing item.

**Comment by Gitchagoomie** [comment]
worked like a charm thanks
