### ISSUE TITLE
Treasures.yml Enchanted_Book data values

### ISSUE THREAD

**Issue by x1p** [mcMMO-Dev/mcMMO#3812]
**Treasure file can't handle enchanted_book**

Example treasures.yml:
```
    ENCHANTED_BOOK:BLAST_PROTECTION:1:
        Amount: 1
        XP: 200
        Rarity: COMMON
```
Server starts, in the log appears:
```
[mcMMO] Invalid material: ENCHANTED_BOOK:BLAST_PROTECTION:1
```
And this error for every enchanted_book
Enchanted books belong in vanilla, so it's odd that it isn't possible so far.

mcMMO 2.2.0 snapshot build 241

**Comment by nossr50** [comment]
I could most likely add this functionality in for the upcoming 2.1.13 dev builds

**Comment by x1p** [comment]
Any news on this?

**Comment by NoFace851** [comment]
Any news about this?

**Comment by andfont** [comment]
I have the same problem, when will it be fixed?

**Comment by electronicboy** [comment]
This is aiming for 2.2, the current configuration system just doesn't support this, and so its' being fixed as part of a huge overhaul of some of the internals

**Comment by andfont** [comment]
I agree but when will it be available please? Because this incident has been open for some time now and it is very important to have some solution to this problem because the vanilla treasure system is very exaggerated and I am not interested! Please tell us the update as soon as possible thanks and good work.
