### ISSUE TITLE
OVERFISHING

### ISSUE THREAD

**Issue by GiraffeCubed** [mcMMO-Dev/mcMMO#3829]
This area is suffering from overfishing, try fishing in a new area.
Improper use of the fishing rod will cause fatigue and wear out the rod!

What the hell is this, it's ruining my servers fishing. I'm not even sure at this point what it actually does, but I want to disable it. What config setting do I change to disable this?

**Comment by nossr50** [comment]
Config options to disable this are in the upcoming config update, which I've been spending 8-12 hours a day on for the last month and a half.

But I'll explain what this is.

In 2.1.19 I improved our AFK/Exploit prevention for Fishing
https://www.spigotmc.org/resources/official-mcmmo.64348/update?update=269228

Previously mcMMO did not warn a player if they were being detected for "abusing fishing". I added some messages to help players understand how the AFK detection for fishing works. On top of this mcMMO now prevents vanilla rewards when it detects "abuse" as well, because vanilla fishing rewards are quite good.

### I'll explain each of the messages and when they trigger.

> This area is suffering from overfishing, try fishing in a new area.

mcMMO prevents players from fishing in close proximity to where they last caught a fish, this stops almost all forms of AFK fishing from being successful.

> Improper use of the fishing rod will cause fatigue and wear out the rod!

This only happens if you recast your fishing rod within 2/10ths of a second of your last cast, ofc you have to take into account client and server network latency on top of this.

This one is to prevent spam from autoclickers from catching fish, in Minecraft if you rapidly cast your fishing rod you will eventually catch fish because Minecraft is super exploitable.

AFK Fishing is a big problem in mcMMO and vanilla Minecraft, and a lot of server owners want this kind of protection.

With that said, **you can actually turn it off in the new config update** which I plan to have out soon, if that's not soon enough for you then you can temporarily downgrade to 2.1.18 or I could push out a hotfix to add a toggle for the old config system.

**Comment by GiraffeCubed** [comment]
Thanks for the quick, and informative reply. I will consider downgrading for now, as a lot of people on my server use fishing machines, though we have custom alerts to notify us of AFK exploiters. The features listed seem great. I'll likely turn off these features on my own server, but I can see how they're useful for the majority, so thanks for including the option!

**Comment by LukeSmith5853** [comment]
Has this been implemented into the config yet? I cannot find it in Build #288

**Comment by Riphtix** [comment]
I would also like to know if this has been implemented yet.

**Comment by nossr50** [comment]
@Riphtix Configuring it is in 2.2 which is not released. You can turn it off in experience.yml the setting is ExploitFix.Fishing

**Comment by Riphtix** [comment]
@nossr50 thank you

**Comment by Klawdek** [comment]
This still has not been fixed and the area gets depleted after a few fish are caught.  Also no information on how far players have to move to reset it.  This feature which was forced on admins and players from a plugin that has nothing to do with fishing is ruining our fishing contest. Furthermore there was no indication as to what plugin was ding it so it took extra time to figure it out. For a long time I thought it was our fishing contest plugin as it is during the fishing contest that most people do their fishing.   If the developer doesn't have the time to make this feature configurable then it should not have been put in place to begin with.  Nobody expects this plugin to regulate fishing.  Please either remove this feature or make it configurable.

**Comment by Momshroom** [comment]
You can disable it in the experience.yml
Also, players don’t need to move at all, simply to cast their rod into a
different water block outside the 3x3 area they cast in last time.

**Comment by Momshroom** [comment]
Also, mcmmo most certainly does have things to do with fishing...

**Comment by Klawdek** [comment]
Thank you for your answer.  I assume it is the setting:
ExploitFix:
    Fishing: true
I looked in a number of the yml files did not expect it there, I expected in the main config. 
Thank you for your help.

**Comment by aytimothy** [comment]
Uhhh... This is broken as of 2.1.151...
