### ISSUE TITLE
[13:03:27 ERROR]: Could not pass event BlockDropItemEvent to mcMMO v2.1.28 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by Emereth** [mcMMO-Dev/mcMMO#3845]
Hi, my console is throwing many Errors:

[13:03:27 ERROR]: Could not pass event BlockDropItemEvent to mcMMO v2.1.28
org.bukkit.event.EventException: null

How can i fix that, or should i ignore that?

Thx for helping^^

**Comment by Quavelen** [comment]
Hey @Emereth, would you mind joining the official mcMMO discord server, so we can help you easier? You can either use **[this invite link](http://discord.mcmmo.org/)**, the button on the official website, or the button on the listing on Spigot.


If not, I'll try to help here. 


That error is specifically caused by you using server software. We currently only support Spigot and Paper, both of which require that you be using a recent version of it due to certain API dependencies. If you are using Spigot, please follow the instructions **[here](https://www.spigotmc.org/wiki/buildtools/)**, and generate a new jar file. If you are using Paper, download it from **[here](https://papermc.io/downloads)**. 

If you use a remote host, you will need to upload the file via FTP. Using the jar file supplied by your host will not work.

**Comment by LukeSmith5853** [comment]
Deleting the spigot.jar file and uploading a new one wont cause any map corruptions or plugin issues will it?

**Comment by Ineusia** [comment]
No, this will not cause any corruption or plugin issues as long as the new one is an **updated** version of spigot.

Make sure that you obtain your build of spigot from the Spigot buildtools linked in Quavelen's informative post above.

**Comment by LukeSmith5853** [comment]
Thank you,
Seems to have worked; no console spam as of yet.
