### ISSUE TITLE
java.lang.NumberFormatException: For input string: "HEARTS"

### ISSUE THREAD

**Issue by vintydong** [mcMMO-Dev/mcMMO#3855]
I encountered this error while loading mcMMO 2.1.30

Spigot should be the latest version
I tried updating mcMMO to 2.1.32 but the same error still came up.

I also tried running the same mcMMO + spigot in another instance. It seems to be a database error.

https://pastebin.com/vgXB3xfS

**Comment by nossr50** [comment]
out of curiosity did you make any edits to the flatfile DB?

**Comment by vintydong** [comment]
No, I didn't

**Comment by nossr50** [comment]
@vintydong I'll take a look at the code and see if I can fix this issue for you. I have to do some errands so it might be a bit.

**Comment by vintydong** [comment]
That's ok 

I don't mind restarting, just don't want the issue to happen again

**Comment by nossr50** [comment]
@vintydong Can I get a copy of your mcmmo.users file?

**Comment by vintydong** [comment]
[mcmmo.zip](https://github.com/mcMMO-Dev/mcMMO/files/3036638/mcmmo.zip)

**Comment by nossr50** [comment]
Alright I ran your DB through a debugger as it loaded

The issue is for some reason the start of your DB entries have invalid characters, I'm not sure if you edited the DB or if some other program did but these are the cause of your issues.

Several of your entires start with >:): which is offsetting the correct values when the array gets split and therefor not loading the data properly

if you delete all the lines starting with >:( that should fix your problem

**Comment by nossr50** [comment]
[mcmmo.zip](https://github.com/mcMMO-Dev/mcMMO/files/3036795/mcmmo.zip)
I edited your users file myself to save you the trouble

**Comment by vintydong** [comment]
Alright thanks so much
