### ISSUE TITLE
The script(.sk) conflicts with the file.

### ISSUE THREAD

**Issue by neptuneex99** [mcMMO-Dev/mcMMO#3956]
I am South Korean.
My server has a script that displays the time on the left side of the nickname.
When you introduce the MCMMO plug-in, the time is marked none:none.
And the Essentials plug-in was also applied with Hangul, but it was changed to English.
I'm sending you a script file.
Please check it out.
[Time.zip](https://github.com/mcMMO-Dev/mcMMO/files/3290935/Time.zip)

**Comment by nossr50** [comment]
Not related to mcMMO

**Comment by neptuneex99** [comment]
As soon as you apply the MCMMO plug-in, it will output as shown in the picture below.
[2019-06-14_23.14.29.zip](https://github.com/mcMMO-Dev/mcMMO/files/3290970/2019-06-14_23.14.29.zip)

**Comment by neptuneex99** [comment]
> mcMMO와 관련 없음




> Not related to mcMMO

As soon as you apply the MCMMO plug-in, it will output as shown in the picture below.
[2019-06-14_23.14.29.zip](https://github.com/mcMMO-Dev/mcMMO/files/3290975/2019-06-14_23.14.29.zip)

**Comment by nossr50** [comment]
You may think this is related to mcMMO, but it is not. If your script is bad, that has nothing to do with me. mcMMO would have no effect on your script.

**Comment by neptuneex99** [comment]
> You may think this is related to mcMMO, but it is not. If your script is bad, that has nothing to do with me. mcMMO would have no effect on your script.

Please review it correctly once and answer again. This error occurs only when MCMMO is applied.

**Comment by nossr50** [comment]
mcMMO does not do a single thing with "scripts"

The contents of your script have nothing even vaguely related to mcMMO in them

Sorry but you're severely misguided

**Comment by nossr50** [comment]
I can guarantee you mcMMO has nothing to do with your script malfunctioning.

First of all, scripting is not inherently supported with Bukkit, so you are using some kind of mod to have this script function. Because scripting is not supported by Bukkit, it means there is no possible way mcMMO is related to your script failing.

Secondly the contents of your script literally have ZERO, and I mean ZERO code, comments, or even a an arrangement of letters that could even be construed as vaguely related to mcMMO.

I'm sorry your script doesn't work but its not my fault, its not related to mcMMO.
