### ISSUE TITLE
How do you disable the Kraken through the files and do you get enchanting books still while fishing?

### ISSUE THREAD

**Issue by Kittyherobrine** [mcMMO-Dev/mcMMO#4017]
I was wondering how do I disable the Kraken from breaking someone's fishing rode? I have it on my little 1.14.4 server and I was wondering if I could turn it off somehow. I was also wondering does having mcMMO fishing on get rid of the chances of finding enchanting books?

**Comment by jdkophazi** [comment]
So I don't know how to disable the kraken, but I have messed with the fishing loot a bit. Enchanted books in standard mcMMO can only be gotten from fishing after level 200, due to needing to have the magical fisher unlocked and fish up a regular book. 

This is the mcMMO treasures file i run on my server. Its main aim is to get rid of most of the stupid mcMMO drops and re-introduce a more classic and logical set of drops.

[treasures.yml.txt.txt](https://github.com/mcMMO-Dev/mcMMO/files/3562543/treasures.yml.txt.txt)

You can change the drops by adding/deleting from the list (approximately the first half of the document if for fishing), and can modify the chances by changing the group it belongs to. I messed around with modifying the group drop rates, but found that, while the preset numbers just ~feel~  little off, they are actually pretty balanced mathematically

**Comment by broccolai** [comment]
Kraken is no longer a part of mcMMO and Enchanted Books are not currently supported by mcMMO, if you'd like to get them you need to disable 'Override Vanilla Drops' in the configs.
