### ISSUE TITLE
[suggestion] Add compatibility for AutoPickup plugin (fishing)

### ISSUE THREAD

**Issue by Zaphara94** [mcMMO-Dev/mcMMO#4129]
It seems there is some sort of conflict between mcMMO and the [AutoPickup Plugin](https://dev.bukkit.org/projects/autopickup). I have spent a few hours testing since a player mentioned that he wasn't getting any mcMMO treasures any more. On my test server i booted up with only mcMMO, and treasures worked fine, however as soon as AutoPickup was also enabled, treasures went right back to vanilla. Even with their AutoPickup toggled off, the treasures were still not mcMMO treasures. 

However, that being said, AutoPickup works fine with mcMMO with bonus drops from ores etc, however does not work properly when auto-smelting the items. If you had 100% double drop chance and 100% double smelting chance with auto pickup and auto smelt on, you would still only get 2 iron ingots per iron ore mined, etc. 

This is not a super priority, however with how 1.13+ servers are so laggy as it is, any performance benefits are appreciated, and AutoPickup certainly helps keep items off the ground! McMMO excavation treasures work fine with AutoPickup as well, going straight into the player's inventory, it seems that only auto smelting and fishing treasures are the only two things that would need to be added compatibility wise. I have written a suggestion to the author of AutoPickup as well.

Thank you for your time, sorry for being so long winded.

**Comment by nossr50** [comment]
@Zaphara94 mcMMO replaces the treasure the same tick it spawns in Minecraft, autopickup is likely grabbing the treasure before mcMMO has had a chance to change it, this could potentially be solved by either AutoPickup's event coming after mcMMO or by having AutoPickup grab items with a 1 tick delay.

**Comment by ThePhilderbeast** [comment]
AutoPickup Dev here, this definitely looks like a bug on your side.

Auto pickup hooks the onItemDrop to place items in the inventory so the only time this would not work on the pick up if mcMMO is not dropping the items.

the auto smelting would be an incompatibility between the plugins as we don't know anything about changes to mechanics introduced by mcMMO so we just follow vanilla smelting, and could possibly be fixed by somone doing the intergration to get that before its smelted.
