### ISSUE TITLE
Korean Translation is not working

### ISSUE THREAD

**Issue by wonyoungb** [mcMMO-Dev/mcMMO#4257]
https://github.com/mcMMO-Dev/mcMMO/pull/4255

That file is so old it contains error in latest version. So I asked support on mcmmo discord but I got nothing.
I kindly request delete translate file on main branch. That file  confusing users like me.*I also tried that file but not working*

**Comment by Quavelen** [comment]
>"not working"

![image](https://user-images.githubusercontent.com/19168008/89724564-3dc83500-d9f4-11ea-8fe1-9b6b71f2a370.png)



Do you perhaps mean it is missing translations, and is incomplete? Because you're more than welcome to contribute to it.

**Comment by nossr50** [comment]
Without more specific details I can't take any action. It appears to be "working" as @Quavelen states.

**Comment by wonyoungb** [comment]
![image](https://user-images.githubusercontent.com/48880431/89724636-a5a46d00-da40-11ea-8965-196df943d689.png)
https://pastebin.com/9x32APqr
Some commands says "an internal error occurred while attempting to perform this command"

**Comment by nossr50** [comment]
@wonyoungb in a few minutes I will be releasing 2.1.140 of mcMMO, update and see if your problem still exists.

**Comment by wonyoungb** [comment]
alrighty

> @wonyoungb in a few minutes I will be releasing 2.1.140 of mcMMO, update and see if your problem still exists.

**Comment by Quavelen** [comment]
Once nossr50 releases the new version, just to be 100% sure @wonyoungb, try this locale file: https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/resources/locale/locale_ko.properties

Save it as `locale_ko.properties` inside the `.. \plugins\mcMMO\locales` directory, and ensure that it is set to `Locale: ko` inside the `config.yml` file. The version you were using was outdated by a fair bit, and I saw was called `ko_KO` instead.

Also, would you mind trying out the latest build of Paper instead of Spigot? Again, just to make 100% certain. 
https://papermc.io/downloads

**Comment by wonyoungb** [comment]
Yeah it's works well after update. Also it's works in Spigot I guess. Thanks
