### ISSUE TITLE
erro locale pt_BR

### ISSUE THREAD

**Issue by llronaldoll** [mcMMO-Dev/mcMMO#4279]
the translation file does not seem to be working, it is only partially translating language, pt_BR

**Comment by nossr50** [comment]
That is because it is not a complete translation, you can help finish the translation if you want. You would need to submit it as a pull request on this GitHub repo.

This is the file in question
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/locale/locale_pt_BR.properties

And here is the master file
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/locale/locale_en_US.properties
