### ISSUE TITLE
Arcane forging permission node not working

### ISSUE THREAD

**Issue by IgnisCraft** [mcMMO-Dev/mcMMO#4337]
I ran into a problem I didn't have running classic mcmmo on 1.15 paper spigot. I noticed at some point, not sure exactly when, but my setup for arcane forging stopped working. Possibly when I updated to 1.16. I also recently purchased the premium version hoping it would be fixed but it wasn't. 
I currently have may_lose_enchants set to false and downgrade to false, and my default group has the  node mcmmo.ability.repair.arcaneforging set to false, and players can unlock arcane forging which I do by applying the node mcmmo.ability.arcaneforging.

This used to work fine, but I noticed that all players were keeping their enchantments regardless of the nodes.

Currently running paper 1.16.3, mcmmo ver 2.1.145

**Comment by IgnisCraft** [comment]
Nothing? No comments?

**Comment by nossr50** [comment]
You need Skills.Repair.ArcaneForging.May_Lose_Enchants in advanced.yml set to true in order to enable the mechanic where mcMMO will remove enchants from items, if this is set to false then mcMMO will never remove enchants and enchants are basically ignored when repairing items, likewise Salvage has a similar setting in advanced.yml

If you then wish to grant certain players the ability to bypass this mechanic you can use this permission node
mcmmo.perks.bypass.salvageenchant for salvage or mcmmo.perks.bypass.repairenchant for repair, I know your original post is only talking about repair but I'd figured I'd mention the salvage permission node as well

Taking away mcmmo.ability.repair.arcaneforging from a player will simply give them the worst result possible when processing repair on enchanted items
