### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by TerdyTheTerd** [mcMMO-Dev/mcMMO#4435]
Thought I would point this out. When trying to import the project I get the following message:
```Could not find artifact net.kyori:adventure-nbt:jar:4.0.0-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/)```

**Comment by IdiomCoder** [comment]
Yes, me to. If anyone can help on this.

**Comment by TerdyTheTerd** [comment]
@IdiomCoder Add this to the pom file under repositories
`        <repository>
            <id>kyori</id>
            <url>https://repo.phoenix616.dev/net/kyori/</url>
        </repository>`

**Comment by Greymagic27** [comment]
Unless it was already in the last dependency update, this could be incorporated into the project pom? Should be easy enough to add and then test

**Comment by nossr50** [comment]
You're responsible for dependencies in your own projects, mcMMO is dependent on kyori so you can add that to your project build setup

Let me know if I've misunderstood this issue

**Comment by TerdyTheTerd** [comment]
Hopefully this doesn't re-open the ticket. The issue is that the above mentioned dependency IS part of the MCMMO project pom file, but it is missing the correct repository, so when trying to build it fails since it cannot find the repo. Not an issue if you are able to track down the correct repository to add, but not everyone is going to know how to do that. I guess either way anyone with valid reasons for needing to compile custom forks should already have the capability to track down missing repo's/dependencies on their own :p unsure what you meant by "your own projects" when this was submitted to MCMMO and references MCMMO...

**Comment by TheBusyBiscuit** [comment]
[KyoriPowered/adventure](https://github.com/KyoriPowered/adventure) should be hosted on maven-central / OSS Sonatype if I remember correctly, so you wouldn't need to add any repository explicitly here.

Though, since the dependency in question is a `-SNAPSHOT`, you may need to explicitly declare Sonatype *Snapshots* as a dependency. And mcMMO does that.
See
[pom.xml - lines 206-209](https://github.com/mcMMO-Dev/mcMMO/blob/master/pom.xml#L206-L209)

Though on some Maven setups it could be the case that snapshots may be ignored by default.
One solution is to explicitly declare the sonatype snapshots repository as a *snapshot* provider.
See
https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository/56145228#56145228

```xml
<repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

You could see if that helps fix your issue rather than relying on the phoenix616 mirror repository (though that of course is also a viable solution).

**Comment by nossr50** [comment]
> Hopefully this doesn't re-open the ticket. The issue is that the above mentioned dependency IS part of the MCMMO project pom file, but it is missing the correct repository, so when trying to build it fails since it cannot find the repo. Not an issue if you are able to track down the correct repository to add, but not everyone is going to know how to do that. I guess either way anyone with valid reasons for needing to compile custom forks should already have the capability to track down missing repo's/dependencies on their own :p unsure what you meant by "your own projects" when this was submitted to MCMMO and references MCMMO...

mcMMO builds correctly on my machine and on our jenkins with the POM it currently has
