### ISSUE TITLE
LegacyFormattingDetected

### ISSUE THREAD

**Issue by broken1arrow** [mcMMO-Dev/mcMMO#4524]
I determined to update the paper (has some bugs). I has look thru first two pages and not see any reports and try to search.

It is a kyori issue, i know it has cause some problems for plugin makers to support it.

````
com.gmail.nossr50.mcmmo.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="**COUNTER-ATTACKED**", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}

````

**Comment by TheBusyBiscuit** [comment]
*I replied this to someone on discord but decided to share it here as well:*

It appears that there was a patch added to Paper which sends a warning to your console if legacy text formatting is detected.

Paper patch:
<https://github.com/PaperMC/Paper/commit/d875bacc2867f3edca955320af715638e92f70e4#diff-d12ae4a656ea3061c18d2d33551af90526d9ef2e390ced2f27d99c6cf1734c26R1808>

Adventure ref:
<https://github.com/KyoriPowered/adventure/blob/master/api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java#L40>

And mcMMO uses a ***lot*** of legacy text formatting.
That's why this will result in a ton of spam.
This is not something you should be worried about, as that is just a warning message for developers, not an actual error message.
It will be a bit of a headache for devs but can be ignored for Server Owners.

<hr />

You could technically add the following environment variable to your server to make this message disappear.
`net.kyori.adventure.text.warnWhenLegacyFormattingDetected=false`
Though I would **not** recommend this, the warning is there for a purpose and I would consider the above *unsafe*.

**Comment by broken1arrow** [comment]
> _I replied this to someone on discord but decided to share it here as well:_
> 
> It appears that there was a patch added to Paper which sends a warning to your console if legacy text formatting is detected.
> 
> Paper patch:
> [PaperMC/Paper@d875bac#diff-d12ae4a656ea3061c18d2d33551af90526d9ef2e390ced2f27d99c6cf1734c26R1808](https://github.com/PaperMC/Paper/commit/d875bacc2867f3edca955320af715638e92f70e4#diff-d12ae4a656ea3061c18d2d33551af90526d9ef2e390ced2f27d99c6cf1734c26R1808)
> 
> Adventure ref:
> https://github.com/KyoriPowered/adventure/blob/master/api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java#L40
> 
> And mcMMO uses a _**lot**_ of legacy text formatting.
> That's why this will result in a ton of spam.
> This is not something you should be worried about, as that is just a warning message for developers, not an actual error message.
> It will be a bit of a headache for devs but can be ignored for Server Owners.
> 
> You could technically add the following environment variable to your server to make this message disappear.
> `net.kyori.adventure.text.warnWhenLegacyFormattingDetected=false`
> Though I would **not** recommend this, the warning is there for a purpose and I would consider the above _unsafe_.

In upstart parameters?

yea, if is not importen, is other more critical info some shall show up not this crap.

**Comment by Faicu** [comment]
> > _I replied this to someone on discord but decided to share it here as well:_
> > It appears that there was a patch added to Paper which sends a warning to your console if legacy text formatting is detected.
> > Paper patch:
> > [PaperMC/Paper@d875bac#diff-d12ae4a656ea3061c18d2d33551af90526d9ef2e390ced2f27d99c6cf1734c26R1808](https://github.com/PaperMC/Paper/commit/d875bacc2867f3edca955320af715638e92f70e4#diff-d12ae4a656ea3061c18d2d33551af90526d9ef2e390ced2f27d99c6cf1734c26R1808)
> > Adventure ref:
> > https://github.com/KyoriPowered/adventure/blob/master/api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java#L40
> > And mcMMO uses a _**lot**_ of legacy text formatting.
> > That's why this will result in a ton of spam.
> > This is not something you should be worried about, as that is just a warning message for developers, not an actual error message.
> > It will be a bit of a headache for devs but can be ignored for Server Owners.
> > You could technically add the following environment variable to your server to make this message disappear.
> > `net.kyori.adventure.text.warnWhenLegacyFormattingDetected=false`
> > Though I would **not** recommend this, the warning is there for a purpose and I would consider the above _unsafe_.
> 
> In upstart parameters?
> 
> yea, if is not importen, is other more critical info some shall show up not this crap.

how to use that enviroment variable? I get this spam too and I want to get rid of it until devs fix it.

**Comment by Warriorrrr** [comment]
The warning was removed from paper in a commit yesterday (https://github.com/PaperMC/Paper/commit/ec90a78595af4cddb6e711ab71de4ee73c59ca49 to be exact), updating your version of paper will resolve any console spam issues related to this.

**Comment by Chew** [comment]
Closing as this issue is no longer valid. Sorry for all the issues :(
