### ISSUE TITLE
creating timings - deprecated behaviour.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4884]
Paper is removing timings.

```
	Line  264: [23:00:31] [Server thread/INFO]: Plugin 'mcMMO' is creating timing 'Commands' - this is deprecated behavior, please report it to the authors: nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike
	Line  265: [23:00:31] [Server thread/INFO]: Plugin 'mcMMO' is creating timing 'Command: ac' - this is deprecated behavior, please report it to the authors: nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike
	Line  266: [23:00:31] [Server thread/INFO]: Plugin 'mcMMO' is creating timing 'Command: pc' - this is deprecated behavior, please report it to the authors: nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike
```

**Comment by nakanotti** [comment]
For more information.

[WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948

**Comment by nossr50** [comment]
I have investigated the issue with the timings and found that we are using ACF for several commands, which has been causing the automatic generation of timings. Although the latest version of ACF does not have this issue, they did not update their version number in their Maven POM. Therefore, in order to get mcMMO working without generating timings, you will need to compile mcMMO and force it to fetch the latest snapshots from its dependencies.

The next version of mcMMO will have the newest version of ACF and will not cause this warning to appear.

**Comment by andrewkm** [comment]
Thanks! :) Confirmed fixed.
