### ISSUE TITLE
Installing mcMMO dramatically reduces fall damage taken by players

### ISSUE THREAD

**Issue by TheBentoBox** [mcMMO-Dev/mcMMO#5023]
I've long felt fall damage on my server was lower than I'd expect, and after some comparisons to vanilla and some plugin searching, I've found mcMMO seems to be the culprit.

To start, see the damage table [here](https://minecraft.wiki/w/Feather_Falling#Usage). With Feather Falling IV and at least two Protection IV armor pieces, players should die from any fall 103 blocks or greater.

The two tests below were done with full Protection IV armor with Feather Falling IV boots, falling from 102 blocks, on a Purpur 1.20.6 server, with no permissions plugin and on a non-op account.

No plugins:
![image](https://github.com/mcMMO-Dev/mcMMO/assets/6902229/fcd88aa9-8423-4fd4-9ae7-8c8c1459636b)

With only mcMMO installed:
![image](https://github.com/mcMMO-Dev/mcMMO/assets/6902229/1ff3acc5-328c-430a-8ad1-bf9188710501)

Here are my versions (latest mcMMO, recent Purpur):
![image](https://github.com/mcMMO-Dev/mcMMO/assets/6902229/4e86168a-f3c6-4126-bceb-a7a72029cc86)

In my testing, with the same gear I need to fall 507 blocks or greater for mcMMO to kill me, so the differential seems to to be almost exactly 5x less fall damage with mcMMO installed.

Let me know if I'm missing something. If not, I'd assume the culprit to be some part of the acrobatics roll code. Thanks.

**Comment by TheBentoBox** [comment]
Also for clarity: in the mcMMO test, I did not proc Roll or Graceful Roll, and I started off as level 0 in Acrobatics.

**Comment by TheBentoBox** [comment]
I would like to bump this bug as IMO it is fairly serious and needs looking at soon.

**Comment by nossr50** [comment]
> I would like to bump this bug as IMO it is fairly serious and needs looking at soon.

I'll prioritize looking into it once I do a bugfix (which will most certainly be the next patch I work on)

**Comment by TheBentoBox** [comment]
Appreciate it bud, thanks for your hard work

**Comment by nossr50** [comment]
I've looked into this, and it seems to be intended behaviour, intended behaviour I forgot about. If you are rolling, you are removing 7 damage from the final damage calculated for fall damage, and if you are graceful rolling, this is removing 14, now that final damage calculated can be dramatically lowered by feather falling.

If you fell from 103 blocks, using the damage table you provided, and assuming you did a graceful roll and had FF IV and Protection II, you would only take 6 damage afterwards because of the amount of damage mcMMO is removing as part of the damage removal from roll.

You can change this behaviour with the config option `Skills.Acrobatics.Roll.DamageThreshold` which governs how much damage a successful Roll will remove (remember, it is doubled for Graceful Roll).

Now mcMMO could change how it is doing things, for example, it could remove less damage if Feather Fall is involved to make it so players can't just jump off a cliff and survive, and arguably, maybe it should.

I'm going to classify this as a feature request since it's more of a balance change than a bug.
Since it's not a bug, it's not as high priority to fix, but I will think about solutions for this problem and see if I can rebalance Roll for enchantments in the near future.

**Comment by nossr50** [comment]
Sorry, I thought I replied to this but it looks like I did not. Sorry for misunderstanding your original report, I will look into it mcMMO is indeed mutating the fall damage, I suspect it is not but I will confirm.

**Comment by TheBentoBox** [comment]
Any update on this?

I want to reiterate my testing scenario. Both pictures are on a freshly installed 1.21.1 Purpur server and represent a 102-block fall; the maximum safe fall with this setup should be 103 blocks:

- Zero plugins, works correctly. I live with minimum health.

![image](https://github.com/user-attachments/assets/d30964a4-154b-4108-a4c7-6ae36efdf54a)

- JUST mcMMO freshly installed, zero config changes, non-OP, default permissions, zero Acrobatics levels. I lose 1.5 hearts instead of 9.5. You can see clearly in the picture that I had zero Acro and did not roll

![image](https://github.com/user-attachments/assets/4b9a43f4-5a3b-49a9-aeb5-86597431045d)

I'm trying to be as clear and fair in my testing as I can but I cannot see anything but mcMMO as the culprit and this seems like a serious game balance issue to me.

**Comment by nossr50** [comment]
My apologies, this fell by the wayside, I'll reprioritize it and look into it soon.
